# Generated by Django 3.1.7 on 2021-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('birthday', models.DateTimeField()),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('hire_date', models.DateField()),
                ('paid_time_off', models.IntegerField()),
                ('user_status', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
