# Generated by Django 2.2.7 on 2021-03-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_auto_20210327_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Accepted', 'Accepted')], max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='app.User')),
            ],
        ),
    ]
