# Generated by Django 3.1.7 on 2021-04-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_department',
            new_name='department',
        ),
    ]
