# Generated by Django 3.1 on 2021-03-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('date_created', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HR', 'HR'), ('Department_manager', 'Department_manager'), ('User', 'User')], max_length=255)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True)),
                ('hire_date', models.DateTimeField(auto_now=True)),
                ('paid_time_off', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Accepted', 'Accepted')], max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.BooleanField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('department_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_leader', to='app.user')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='app.user')),
            ],
        ),
    ]
