# Generated by Django 2.2.7 on 2021-03-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210321_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='date_deleted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
