# Generated by Django 2.2.7 on 2021-03-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
