# Generated by Django 2.2.7 on 2021-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Department_manager', 'Department_manager'), ('User', 'User')], default='User', max_length=255),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
