# Generated by Django 2.2.7 on 2021-03-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210321_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='date_deleted',
        ),
    ]
