# Generated by Django 2.2.7 on 2021-03-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_department_date_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='users',
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='app.User'),
        ),
    ]
