# Generated by Django 2.2.7 on 2021-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
