# Generated by Django 2.2.7 on 2021-03-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('department_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_leader', to='app.User')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='app.User')),
            ],
        ),
    ]
