# Generated by Django 3.1.7 on 2021-04-03 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_department_department_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
